### ISSUE TITLE
Report Download in Excel format Fails

### ISSUE THREAD

**Issue by muralithiyagarajan** [bodastage/bts-ce-lite#115]
Version: 0.3.0-beta.1
OS: Windows 10

**Comment by muralithiyagarajan** [comment]
[2019-09-25 12:16:34.140] [error] TypeError: Cannot read property 'DATETIME' of undefined
    at C:\Users\ADMIN\AppData\Local\Programs\Boda-Lite\resources\app.asar\background\background-utils.js:290:26
    at Row.eachCell (C:\Users\ADMIN\AppData\Local\Programs\Boda-Lite\resources\app.asar\node_modules\exceljs\dist\es5\doc\row.js:150:11)
    at results.rows.forEach (C:\Users\ADMIN\AppData\Local\Programs\Boda-Lite\resources\app.asar\background\background-utils.js:287:32)
    at Array.forEach (<anonymous>)
    at generateExcelFromQuery (C:\Users\ADMIN\AppData\Local\Programs\Boda-Lite\resources\app.asar\background\background-utils.js:283:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by erssebaggala** [comment]
Resolved by PR #116
