### ISSUE TITLE
uws\src\networking.h(7): fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file

### ISSUE THREAD

**Issue by erssebaggala** [bodastage/bts-ce-lite#5]
c:\users\emmanuel\documents\bodastage\code_repos\pr\bts-ce-lite\node_modules\xrs\node_modules\uws\src\networking.h(7): fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory (compiling source file ..\src\addon.cpp) [C:\Users\Emmanuel\Documents\Bodastage\code_repos\pr\bts-ce-lite\node_modules\xrs\node_modules\uws\build\uws.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Emmanuel\Documents\Bodastage\code_repos\pr\bts-ce-lite\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Emmanuel\\Documents\\Bodastage\\code_repos\\pr\\bts-ce-lite\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=4.2.0" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\Users\Emmanuel\Documents\Bodastage\code_repos\pr\bts-ce-lite\node_modules\xrs\node_modules\uws
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by erssebaggala** [comment]
Related issues:
* https://github.com/electron/electron-rebuild/issues/175
* https://github.com/electron-userland/electron-forge/issues/419

**Comment by erssebaggala** [comment]
Was fixed by running a fresh package installation with **yarn install**
